Document units of bus carriers
PyPSA/pypsa-eur-sec pull request #245
Opened 2022-06-28 16:54 UTC by Irieo

add explicit documentation of the unit of each bus' carrier
this addresses the issue https://github.com/PyPSA/pypsa-eur-sec/issues/134#event-6804897616

Bus [unit]:

- electricity, low voltage [MWh_el]
- home battery, battery, batteries in transport  [MWh_el]

- coal, nuclear and oil  [MWh_th]
- ice in transport [MWh_th]
- buses in heat sector [MWh_th]
- biogas and biomas [MWh_th]

- co2 atmosphere, co2 stored, process emissions [t_co2]

- H2, shipping_hydrogen_liquefaction [MWh_LHV]
- gas for industry [MWh_LHV]

2022-06-29 07:54 UTC, fneum requested changes
This is very handy!

Oil and biomass should also be labelled as LHV, I think.

2022-06-29 07:54 UTC, fneum commented on scripts/prepare_sector_network.py
> +    unit="MWh_LHV" if carrier=="gas" else "MWH_th"
```suggestion
    unit = "MWh_LHV" if carrier == "gas" else "MWh_th"
```

2022-06-29 07:54 UTC, fneum commented on scripts/prepare_sector_network.py
> +# %%
```suggestion
```

2022-06-30 15:40 UTC, Irieo commented
> This is very handy!
> Oil and biomass should also be labelled as LHV, I think.

@fneum done.

2022-06-30 15:43 UTC, merged